### ISSUE TITLE
Criar Esquema de banco de dados

### ISSUE THREAD

**Issue by felipemantoan** [MatheusHNSantos/TCC-FATEC_2017-PAVG#3]
- [x] Criar tabela de pessoas
- [x] Criar tabela de usuários
- [x] Criar tabela de clientes(pessoa_fisica)
- [x] Criar tabela de funcionários
- [x] Criar tabela de fornecedores (pessoa_juridica)
- [x] Criar Tabela de produtos
- [x] Criar Tabela Tipo de produtos
- [x] Criar Tabela de Ingredientes 
- [x] Criar Tabela de Pedidos 
- [ ] Criar tabela de logs
- [ ] Criar Tabela de Histórico de Vendas

**Comment by felipemantoan** [comment]
- [x] Criar tabela de endereço
- [x] Criar tabela de telefones

**Comment by MatheusHNSantos** [comment]
- [x] Criar Tabela de Vendas
- [x] Criar Tabela de Itens de Venda

**Comment by MatheusHNSantos** [comment]
Adicionar método para impressão de cupom fiscal na tabela Sale (Venda)
